FROM centos:7
MAINTAINER Jacob McCann <jmccann.git@gmail.com>

RUN yum -y install pygpgme yum-utils

ADD chef_stable.repo /etc/yum.repos.d/chef_stable.repo
RUN yum -y install \
      chef-CHEF_VER \
      sudo && \
    yum -y update && yum clean all

RUN rm -f /etc/yum.repos.d/chef_stable.repo

# Sudo stuff for kitchen-inspec
RUN echo 'chef ALL=(root) NOPASSWD: ALL' > /etc/sudoers.d/chef
RUN echo 'Defaults!ALL !requiretty' >> /etc/sudoers.d/chef
